<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.*" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PostForge.Application\PostForge.Application.csproj" />
    <ProjectReference Include="..\PostForge.Infrastructure.DAL\PostForge.Infrastructure.DAL.csproj" />
    <ProjectReference Include="..\PostForge.Infrastructure.Messaging.ServiceBus\PostForge.Infrastructure.Messaging.ServiceBus.csproj" />
    <ProjectReference Include="..\PostForge.Infrastructure\PostForge.Infrastructure.csproj" />
    <ProjectReference Include="..\PostForge.Infrastructure.Providers\PostForge.Infrastructure.Providers.csproj" />
    <ProjectReference Include="..\PostForge.Providers.Anthropic\PostForge.Providers.Anthropic.csproj" />
    <ProjectReference Include="..\PostForge.Providers.DallE\PostForge.Providers.DallE.csproj" />
    <ProjectReference Include="..\PostForge.Providers.Facebook\PostForge.Providers.Facebook.csproj" />
    <ProjectReference Include="..\PostForge.Providers.GoogleGemini\PostForge.Providers.GoogleGemini.csproj" />
    <ProjectReference Include="..\PostForge.Providers.Instagram\PostForge.Providers.Instagram.csproj" />
    <ProjectReference Include="..\PostForge.Providers.MicrosoftFoundry\PostForge.Providers.MicrosoftFoundry.csproj" />
    <ProjectReference Include="..\PostForge.Providers.OpenAI\PostForge.Providers.OpenAI.csproj" />
    <ProjectReference Include="..\PostForge.Providers.StableDiffusion\PostForge.Providers.StableDiffusion.csproj" />
    <ProjectReference Include="..\PostForge.Providers.TikTok\PostForge.Providers.TikTok.csproj" />
    <ProjectReference Include="..\PostForge.Providers.YouTube\PostForge.Providers.YouTube.csproj" />
  </ItemGroup>

</Project>
