using PostForge.Domain.Providers;
using PostForge.Domain.Providers.Contracts;

namespace PostForge.Providers.Fake;

public sealed class FakeAiTextProvider : IAiTextProvider
{
    public string ProviderKey => "FAKE";

    public Task<string> GenerateCaptionAsync(CaptionRequest request, CancellationToken ct)
    {
        var tone = request.Tone is null ? string.Empty : $" [{request.Tone}]";
        var platform = request.PlatformIdentifier is null ? string.Empty : $" for {request.PlatformIdentifier}";

        return Task.FromResult($"{request.Brief}{tone}{platform} — generated by FakeAiTextProvider");
    }
}